export default

[
    {
        id: 1,
        CategoryName: "Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/81uTb5UwUgL._AC_UL600_FMwebp_QL65_.jpg",
        price: 999,
        Subtitle: "Mens Shirt",
        quantity: 1,
        DiscountedPrice: 799,
        description: "Men's Regular Fit Casual Shirt",
        Ratingstar: "⭐",
        Rating: 1
    },
    {
        id: 2,
        CategoryName: "Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/81b5cEI0MJL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1199,
        Subtitle: "Mens Shirt",
        quantity: 1,
        DiscountedPrice: 899,
        description: "Men Allday Fresh Buttondown ",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 3,
        CategoryName: "Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/717kxMoZiAL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1199,
        Subtitle: "Mens Shirt",
        quantity: 1,
        DiscountedPrice: 899,
        description: "Slim Fit Cotton Casual",
        Ratingstar: "⭐⭐⭐",
        Rating: 3
    },
    {
        id: 4,
        CategoryName: "Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/71Gmi8W2vxL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1499,
        Subtitle: "Mens Shirt",
        quantity: 1,
        DiscountedPrice: 1299,
        description: "Men's Regular Fit Casual Shirt",
        Ratingstar: "⭐",
        Rating: 1
    },
    {
        id: 5,
        CategoryName: "T-Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/51erlDVGq1L._AC_UL600_FMwebp_QL65_.jpg",
        price: 1499,
        Subtitle: "Mens T-Shirt",
        quantity: 1,
        DiscountedPrice: 1299,
        description: "Men Polo Shirt",
        Ratingstar: "⭐⭐⭐",
        Rating: 3
    },
    {
        id: 6,
        CategoryName: "T-Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/61vmxtHv4IL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1999,
        Subtitle: "Mens T-Shirt",
        quantity: 1,
        DiscountedPrice: 1599,
        description: "Men 100% Cotton Tshirt",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 7,
        CategoryName: "T-Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/71V4RsIUADL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1999,
        Subtitle: "Mens T-Shirt",
        quantity: 1,
        DiscountedPrice: 1599,
        description: "Men's Regular Fit Polo Shirt",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 8,
        CategoryName: "T-Shirt",
        ProductImage: "https://m.media-amazon.com/images/I/51XkLH567OL._AC_UL600_FMwebp_QL65_.jpg",
        price: 2299,
        Subtitle: "Mens T-Shirt",
        quantity: 1,
        DiscountedPrice: 1899,
        description: "Men's Regular Fit Polo Shirt",
        Ratingstar: "⭐⭐⭐⭐⭐ 5",
        Rating: 5
    },
    {
        id: 9,
        CategoryName: "Hoodie",
        ProductImage: "https://m.media-amazon.com/images/I/81sL1frWY9L._AC_UL600_FMwebp_QL65_.jpg",
        price: 2299,
        Subtitle: "Mens Hoodie",
        quantity: 1,
        DiscountedPrice: 1899,
        description: "Men Hooded Sweatshirt",
        Ratingstar: "⭐⭐",
        Rating: 2
    },
    {
        id: 10,
        CategoryName: "Hoodie",
        ProductImage: "https://m.media-amazon.com/images/I/81O4ylyiYzL._AC_UL600_FMwebp_QL65_.jpg",
        price: 2999,
        Subtitle: "Mens Hoodie",
        quantity: 1,
        DiscountedPrice: 1899,
        description: "Men's Cotton Hooded Hoodie",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 11,
        CategoryName: "Hoodie",
        Subtitle: "Mens Hoodie",
        ProductImage: "https://m.media-amazon.com/images/I/51eWeMAh9dL._AC_UL600_FMwebp_QL65_.jpg",
        price: 2000,
        quantity: 1,
        DiscountedPrice: 1400,
        description: "Men's Fleece Hooded Hoodie",
        Ratingstar: "⭐⭐⭐⭐⭐ 5",
        Rating: 5
    },
    {
        id: 12,
        CategoryName: "Hoodie",
        ProductImage: "https://m.media-amazon.com/images/I/91mSkX-LlwL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1499,
        Subtitle: "Mens Hoodie",
        quantity: 1,
        DiscountedPrice: 1299,
        description: "Trendy Printed Men's Hoodies",
        Ratingstar: "⭐⭐⭐",
        Rating: 3
    },
    {
        id: 13,
        CategoryName: "Jeans",
        ProductImage: "https://m.media-amazon.com/images/I/81tMkvCXlIL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1799,
        Subtitle: "Mens Jeans",
        quantity: 1,
        DiscountedPrice: 1499,
        description: "Men's Tapered Jeans",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 14,
        CategoryName: "Jeans",
        ProductImage: "https://m.media-amazon.com/images/I/51UpvY8td3L._AC_UL600_FMwebp_QL65_.jpg",
        price: 1999,
        Subtitle: "Mens Jeans",
        quantity: 1,
        DiscountedPrice: 1599,
        description: "Men's Skinny Jeans",
        Ratingstar: "⭐⭐",
        Rating: 2
    },
    {
        id: 15,
        CategoryName: "Jeans",
        ProductImage: "https://m.media-amazon.com/images/I/616xchp1ECL._AC_UL600_FMwebp_QL65_.jpg",
        price: 2599,
        Subtitle: "Mens Jeans",
        quantity: 1,
        DiscountedPrice: 2199,
        description: "Men's Regular Jeans",
        Ratingstar: "⭐⭐⭐⭐⭐ 5",
        Rating: 5
    },
    {
        id: 16,
        CategoryName: "Jeans",
        ProductImage: "https://m.media-amazon.com/images/I/71a3OycnGYL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1299,
        Subtitle: "Mens Jeans",
        quantity: 1,
        DiscountedPrice: 899,
        description: "Men's Relaxed Fit Jeans",
        Ratingstar: "⭐⭐",
        Rating: 2
    },
    {
        id: 17,
        CategoryName: "Jacket",
        ProductImage: "https://m.media-amazon.com/images/I/61G1ZLzdBeS._AC_UL600_FMwebp_QL65_.jpg",
        price: 1499,
        Subtitle: "Mens Jacket",
        quantity: 1,
        DiscountedPrice: 1199,
        description: "Men's Denim Jacket",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    },
    {
        id: 18,
        CategoryName: "Jacket",
        ProductImage: "https://m.media-amazon.com/images/I/71IPX82oUDL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1799,
        Subtitle: "Mens Jacket",
        quantity: 1,
        DiscountedPrice: 1499,
        description: "Regular Fit Bomber Jacket",
        Ratingstar: "⭐⭐⭐⭐⭐ 5",
        Rating: 5
    },
    {
        id: 19,
        CategoryName: "Jacket",
        ProductImage: "https://m.media-amazon.com/images/I/610ysTt7-3L._AC_UL600_FMwebp_QL65_.jpg",
        price: 1299,
        Subtitle: "Mens Jacket",
        quantity: 1,
        DiscountedPrice: 999,
        description: "Men Lightweight Jacket",
        Ratingstar: "⭐⭐",
        Rating: 2
    },
    {
        id: 20,
        CategoryName: "Jacket",
        ProductImage: "https://m.media-amazon.com/images/I/71FdmTgg0hL._AC_UL600_FMwebp_QL65_.jpg",
        price: 1299,
        Subtitle: "Mens Jacket",
        quantity: 1,
        DiscountedPrice: 999,
        description: "Men Men's Jacket",
        Ratingstar: "⭐⭐⭐⭐",
        Rating: 4
    }
]


